const USE_FIXED_VIEW = false;
const CANVAS_SIZE = 720;

const VIEWPORT_SIZE = USE_FIXED_VIEW ? 16 : 15;
const VIEWPORT_OFFSET = Math.floor(VIEWPORT_SIZE / 2);
const SCALE = CANVAS_SIZE / VIEWPORT_SIZE;





